language: ruby
services:
- docker
git:
  depth: false
install: skip
stages:
- test
- stable package
- nightly package
script:
- 'docker-compose run app-deb10 make test

  '
jobs:
  include:
  - stage: test
    name: Run rake tests
    script:
    - docker-compose run app-deb10 make test
  - stage: test
    name: Rubocop and Bundle Audit
    script:
    - docker-compose run app-deb10 make lint
  - stage: stable package
    if: branch != master OR tag =~ ^.*$
    name: Stable Debian 10(buster) package
    script: &1
    - 'docker-compose run --name virtualizm-build-deb10 app-deb10 make package &&
      docker commit virtualizm-build-deb10 virtualizm:build-deb10

      '
    deploy:
      skip_cleanup: true
      provider: script
      script: docker run --name virtualizm-deploy-deb10 virtualizm:build-deb10 ci/deploy.sh
        "$API_ENDPOINT" buster "${TRAVIS_TAG%.*}" main /build/*.deb
      on:
        tags: true
        condition: "$TRAVIS_TAG != *-master*"
        repo: virtualizm/virtualizm-api
  - stage: nightly package
    if: branch = master
    name: Nightly Debian 10(buster) package
    script: *1
    deploy:
      skip_cleanup: true
      provider: script
      script: docker run --name virtualizm-deploy-deb10 virtualizm:build-deb10 ci/deploy.sh
        "$API_ENDPOINT" buster nightly main /build/*.deb
      on:
        all_branches: true
        repo: virtualizm/virtualizm-api
env:
  global:
    secure: ds3HlKjxwUBToXzI4Tp0gsy65d55OQ3muC9F9A3/OdlxzUlkE8w+7EKSdRnN+ppJ2kWIi0uWsQAJ/VEOfz+XXuYAT5CJL6GApLxP/fohKuzDqkDRfVztjKLY/+rxgi4q+fATdULspwIzgRMUWKP+bMQvGlaiZfJqI+XVz5ZSRyp41UA+ZtUEqYgUuVJU5qHIQykA6P5ZmHzmhwKXjKEklKscfwtKQ5KCIcJDx2LSafFFm+Lc4lEuG5XpGepfx1MLS9gPg4zAxUxmMEuaKFm4usP1AFVPkNXPwZw3xEu1hUcFY9YPqHtBaCCs9x37KbeHqS4sOxS5muBRAuRZepjUIuAc8TetMMaHwcwN0aAU4auDok7rPAgt53HInNVgVsLwQV/sm8XkxIZ9GesJwk+914Dfi5may8s3SHm7aBm9+RXPoQWCXi8ZTZaLGww17AKgD6Ir9H7zvtTJTn71wxNatbDAtfyj6xkRM2umZrbfpcoP42JhpLzw6U+n0otYPkm8gEItWkx/M+kyd6y8Nti+czT8RYaH8NuOQeAvzJcXcdYhwiVvwqC3rirOtq13C3vBzjI1WvFo6lq/LRSvt8VQp6eZXxVK94pe5KL/VmlF5vbZzWr/pybTSKgANaDMr/fWynvzUeNcLWezMC7Daw1BF8nWbGUsZSwDZKezTYMUn/k=
